version: "3.8"

services:
  bank-service:
    image: starciacademy/reliability-and-resilience-patterns-timeouts-bank-service:latest
    build:
      context: ../bank-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - starci-network

  client-service:
    image: starciacademy/reliability-and-resilience-patterns-timeouts-client-service:latest
    build:
      context: ../client-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - bank-service
    networks:
      - starci-network

networks:
  starci-network:
    external: true
    name: starci-network
