version: "3.8"

services:
  inventory-service:
    image: starciacademy/reliability-and-resilience-patterns-circuit-inventory-service:latest
    build:
      context: ../inventory-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - starci-network

  api-gateway:
    image: starciacademy/reliability-and-resilience-patterns-circuit-api-gateway:latest
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service
    networks:
      - starci-network

networks:
  starci-network:
    external: true
    name: starci-network
